name: Run typecheck
on:
  pull_request:
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn --frozen-lockfile
      - run: yarn bootstrap
      - run: yarn typecheck
